# Generated by Django 5.0.6 on 2026-09-08 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_number', models.CharField(editable=False, max_length=25, unique=True)),
                ('project_type', models.CharField(choices=[('ON_GRID', 'On-Grid'), ('OFF_GRID', 'Off-Grid'), ('HYBRID', 'Hybrid')], default='ON_GRID', max_length=20)),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('GOVERNMENT', 'Government')], default='RESIDENTIAL', max_length=20)),
                ('capacity_kw', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('project_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subsidy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('stage', models.CharField(choices=[('REGISTERED', 'Registered'), ('SURVEY', 'Site Survey'), ('DESIGN', 'Design & Approval'), ('MATERIAL_DISPATCH', 'Material Dispatch'), ('INSTALLATION', 'Installation'), ('NET_METERING', 'Net Metering'), ('COMMISSIONED', 'Commissioned'), ('CLOSED', 'Closed')], default='REGISTERED', max_length=20)),
                ('expected_completion', models.DateField(blank=True, null=True)),
                ('commissioned_on', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='customers.customer')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('REGISTERED', 'Registered'), ('SURVEY', 'Site Survey'), ('DESIGN', 'Design & Approval'), ('MATERIAL_DISPATCH', 'Material Dispatch'), ('INSTALLATION', 'Installation'), ('NET_METERING', 'Net Metering'), ('COMMISSIONED', 'Commissioned'), ('CLOSED', 'Closed')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('note', models.TextField(blank=True)),
                ('is_done', models.BooleanField(default=False)),
                ('done_on', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CARD', 'Card')], default='BANK', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('paid_on', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project')),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
    ]
