# Generated by Django 5.0.6 on 2026-09-08 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('projects', '0001_initial'),
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('NEFT', 'NEFT/RTGS')], default='BANK', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=140)),
                ('paid_on', models.DateField(default=django.utils.timezone.now)),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='service.amccontract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_number', models.CharField(editable=False, max_length=25, unique=True)),
                ('category', models.CharField(choices=[('SALARY', 'Salaries'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('TRANSPORT', 'Transport / Logistics'), ('MARKETING', 'Marketing'), ('TOOLS', 'Tools & Equipment'), ('MISC', 'Miscellaneous')], default='MISC', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('NEFT', 'NEFT/RTGS')], default='BANK', max_length=10)),
                ('spent_on', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.project')),
            ],
            options={
                'ordering': ['-spent_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetMetering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discom', models.CharField(blank=True, max_length=120, verbose_name='DISCOM')),
                ('application_no', models.CharField(blank=True, max_length=60)),
                ('consumer_no', models.CharField(blank=True, max_length=60)),
                ('sanctioned_load_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('APPLIED', 'Applied'), ('INSPECTION', 'Inspection Scheduled'), ('APPROVED', 'Approved'), ('METER_INSTALLED', 'Meter Installed'), ('COMMISSIONED', 'Commissioned'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=16)),
                ('applied_on', models.DateField(blank=True, null=True)),
                ('approved_on', models.DateField(blank=True, null=True)),
                ('meter_installed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='net_metering', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubsidyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(editable=False, max_length=25, unique=True)),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Application Pending'), ('APPLIED', 'Applied'), ('SANCTIONED', 'Sanctioned'), ('DISBURSED', 'Disbursed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('application_no', models.CharField(blank=True, max_length=60)),
                ('applied_on', models.DateField(blank=True, null=True)),
                ('sanctioned_on', models.DateField(blank=True, null=True)),
                ('disbursed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidy_claims', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_claim', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('NEFT', 'NEFT/RTGS')], default='BANK', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=140)),
                ('paid_on', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.purchaseorder')),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
    ]
